### PR TITLE
Time series of net event

### PR DESCRIPTION
**Pull request by mark-edmondson-jones**

### CODE REVIEW

**Comment by stefanoborini** [comment]
There's a conflict to fix.

**Comment by mark-edmondson-jones** [comment]
Agreed.  I have reviewed and looks fine to me.  Git won't let me approve my own changes though.

**Comment by stefanoborini** [comment]
There have been changes both on master and on your branch on the same code. You need to resolve these conflicts before moving further.

**Comment by mark-edmondson-jones** [comment]
This seems to be caused by file renamings.  plot_timeseries is based on previous code with changes to remove hardcoded treatments.  ae_timeseries includes more functionality changes.  These include removing the hardcoded treatments (slightly different coding) but also functionality to allow all, selected or one AE to be plotted.
Recommend code from ae_timeseries is merged with roxygen comments from plot_timeseries.
Check from plot_timeseries for any records matching on term (lines 31-34) could be inserted after line 14 in ae_timeseries to retain this check.

**Pull request closed without merging**
