### PR TITLE
Fixed incorrect scale for limited tendril plotting.

### LINKED ISSUE #91: Incorrect scale for limited tendril plotting in interactive mode
image001

In the interactive case, the scale is wrong since there is not enough tendrils to span between non-significant and highly significant. The scale should be limited to 0 to -3, with 0 being bluish and -3 blackish.

### PR DESCRIPTION
**Pull request by stefanoborini**
Fixes #91

### CODE REVIEW

**Comment by stefanoborini** [comment]
@Karpefors good?

**Comment by Karpefors** [comment]
Essentially I would like to have a scale that is hard-coded between -3 and 0 (because log(p) can go from -infinity to zero, and we are transforming all values smaller than -3 to be -3).
From the code I’m not sure that that is what is happening. If it is, I’m happy.

**Comment by stefanoborini** [comment]
@Karpefors the limits is defined in colorfuncs.R as

```
tendril_palette <- function() {
  # Returns a list containing information about the palette we use
  grpalette <- grDevices::colorRampPalette( c( "grey15", "red", "darkorange", "gold", "cornflowerblue"  ) )( 5 )
  values <- scales::rescale(c(-3, -1.3, -1, -0.3, 0))
  limits <- c(-3, 0)
  ret <- list(
    grpalette = grpalette,
    values = values,
    limits = limits
  )
  return(ret)
}
```

This function returns the smart, gradual palette that we need, and the limits are intrinsically from -3 to 0. The reason why it wasn't used is that I incorrectly used zmax/zmin instead of cmax/cmin, and that I was still using the old palette format.

This is the new result (set aside the incorrect label, this was in a separate branch)

Screenshot 2020-01-21 at 09 40 34

**Comment by stefanoborini** [comment]
Seems to satisfy the requirement. merging.

**Pull request merged**
